SELECT 
`abarrotes`, `cedis`, `mercado`, `pedregal`, `tienda`, `trincheras`, `tenencia`, `ultra`, `tijeras`, `ctz_first`.`id_cotizacion`, `prod`.`registrazo`, 
`fac`.`codigo_factura`, `ctz_first`.`fecha_registro`, `prod`.`estatus`, `prod`.`color`, `prod`.`colorp`, `prod`.`codigo`, `prod`.`nombre` AS `producto`, `prod`.`id_producto`
, UPPER(proveedor_first.nombre) AS proveedor_first, `proveedor_first`.`cargo`, `ctz_first`.`precio` AS `precio_firsto`, `sto`.`cantidad` as `stocant`, 
IF((ctz_first.precio_promocion >0), `ctz_first`.`precio_promocion`, ctz_first.precio) AS precio_first, `my`.`id_mayoreo`, `ctz_first`.`observaciones` AS `promocion_first`, 
`ctz_first`.`observaciones` AS `observaciones_first`, `prod`.`precio_sistema`, `prod`.`precio_four`, UPPER(proveedor_next.nombre) AS proveedor_next, `ctz_next`.`fecha_registro` 
AS `fecha_next`, `ctz_next`.`observaciones` AS `promocion_next`, `ctz_next`.`precio` AS `precio_nexto`, IF((ctz_next.precio_promocion >0), `ctz_next`.`precio_promocion`, 
	ctz_next.precio) AS precio_next, UPPER(proveedor_nxts.nombre) AS proveedor_nxts, `ctz_nxts`.`fecha_registro` AS `fecha_nxts`, `ctz_nxts`.`observaciones` AS `promocion_nxts`, 
tz_nxts`.`precio` AS `precio_nxtso`, IF((ctz_nxts.precio_promocion >0), `ctz_nxts`.`precio_promocion`, ctz_nxts.precio) AS precio_nxts, `ctz_maxima`.`precio` AS `precio_maximo`, 
AVG(c.precio) AS precio_promedio, `prod`.`id_familia`, `prod`.`familia` AS `familia` 
FROM `prodandprice` `prod` 
LEFT JOIN `cotizaciones` `c` ON `prod`.`id_producto` = `c`.`id_producto` AND WEEKOFYEAR(c.fecha_registro) = 13 AND `c`.`estatus` = 1 LEFT JOIN `cotizaciones` `ctz_first` ON `ctz_first`.`id_cotizacion` = (SELECT ctz_min.id_cotizacion FROM cotizaciones ctz_min LEFT JOIN usuarios uss on ctz_min.id_proveedor = uss.id_usuario	WHERE prod.id_producto = ctz_min.id_producto AND WEEKOFYEAR(ctz_min.fecha_registro) = 13 AND `ctz_min`.`precio_promocion` = (SELECT MIN(ctz_min_precio.precio_promocion) FROM cotizaciones ctz_min_precio WHERE ctz_min_precio.id_producto = ctz_min.id_producto AND `ctz_min_precio`.`estatus` = 1 AND WEEKOFYEAR(ctz_min_precio.fecha_registro) = 13) ORDER BY uss.orden ASC LIMIT 1) LEFT JOIN `cotizaciones` `ctz_maxima` ON `ctz_maxima`.`id_cotizacion` = (SELECT ctz_max.id_cotizacion FROM cotizaciones ctz_max WHERE ctz_first.id_producto = ctz_max.id_producto AND `ctz_max`.`precio` = (SELECT MAX(ctz_max_precio.precio) FROM cotizaciones ctz_max_precio WHERE ctz_max_precio.id_producto = ctz_max.id_producto AND `ctz_max_precio`.`estatus` = 1 AND WEEKOFYEAR(ctz_max_precio.fecha_registro) = 13) LIMIT 1) LEFT JOIN `cotizaciones` `ctz_next` ON `ctz_next`.`id_cotizacion` = (SELECT cott.id_cotizacion FROM cotizaciones cott WHERE cott.id_producto = ctz_first.id_producto AND `cott`.`estatus` = 1 AND `cott`.`precio_promocion` >= `ctz_first`.`precio_promocion` AND WEEKOFYEAR(cott.fecha_registro) = 13 AND `cott`.`id_proveedor` <> ctz_first.id_proveedor ORDER BY cott.precio ASC LIMIT 1 ) LEFT JOIN `cotizaciones` `ctz_nxts` ON `ctz_nxts`.`id_cotizacion` = (SELECT cots.id_cotizacion FROM cotizaciones cots WHERE cots.id_producto = ctz_first.id_producto AND `cots`.`estatus` = 1 AND `cots`.`precio_promocion` >= `ctz_next`.`precio_promocion` AND WEEKOFYEAR(cots.fecha_registro) = 13 AND `cots`.`id_proveedor` <> `ctz_first`.`id_proveedor` AND `cots`.`id_proveedor` <> ctz_next.id_proveedor ORDER BY cots.precio ASC LIMIT 1 ) LEFT JOIN `usuarios` `proveedor_first` ON `ctz_first`.`id_proveedor` = `proveedor_first`.`id_usuario` LEFT JOIN `usuarios` `proveedor_next` ON `ctz_next`.`id_proveedor` = `proveedor_next`.`id_usuario` LEFT JOIN `usuarios` `proveedor_nxts` ON `ctz_nxts`.`id_proveedor` = `proveedor_nxts`.`id_usuario` LEFT JOIN `stocks` `sto` ON `prod`.`id_producto` = `sto`.`id_producto` LEFT JOIN `prodcaja` `fac` ON `prod`.`id_producto` = `fac`.`id_prodfactura` LEFT JOIN `mayoreo` `my` ON `prod`.`codigo` = `my`.`codigo` WHERE `ctz_first`.`id_proveedor` = '2' AND `prod`.`estatus` = 1 GROUP BY `prod`.`nombre` ORDER BY `prod`.`id_familia` ASC, `prod`.`nombre` ASC